### ISSUE TITLE
Add Secret to GitHub Actions Build Process

### ISSUE THREAD

**Issue by lsteen89** [lsteen89/SteenBudgetSolution#1]
### Task: Add Secret to GitHub Actions Build Process

**Description**:
Integrate the newly added secret (`SMTP_PASSWORD`) into the GitHub Actions workflow to enable secure access to the SMTP password.

**Steps**:
- [x] Access `.github/workflows/your_workflow.yml`
- [x] Add `SMTP_PASSWORD` as an environment variable in the workflow file:
  ```yaml
  env:
    SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
- [x] Test the workflow to ensure the secret is accessible.
